-- MySQL Script generated by MySQL Workbench
-- 12/05/16 14:37:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema foodplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `camping_spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `camping_spot` ;

CREATE TABLE IF NOT EXISTS `camping_spot` (
  `spot_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(6) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`spot_id`),
  UNIQUE INDEX `spot_id_UNIQUE` (`spot_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `age` INT NOT NULL,
  `mobile` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `votes_left` INT NOT NULL,
  `fav_food` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `mobile_UNIQUE` (`mobile` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ticket` ;

CREATE TABLE IF NOT EXISTS `ticket` (
  `ticket_number` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `order_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`ticket_number`),
  INDEX `fk_ticket_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_ticket_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `competition` ;

CREATE TABLE IF NOT EXISTS `competition` (
  `code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `location` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reservation` ;

CREATE TABLE IF NOT EXISTS `reservation` (
  `user_id` INT NOT NULL,
  `spot_id` INT NOT NULL,
  `res_number` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `num_of_people` INT NOT NULL,
  INDEX `fk_user_has_camping_spot_camping_spot1_idx` (`spot_id` ASC),
  INDEX `fk_user_has_camping_spot_user_idx` (`user_id` ASC),
  PRIMARY KEY (`res_number`),
  CONSTRAINT `fk_user_has_camping_spot_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_camping_spot_camping_spot1`
    FOREIGN KEY (`spot_id`)
    REFERENCES `camping_spot` (`spot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `competitor` ;

CREATE TABLE IF NOT EXISTS `competitor` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `img_src` VARCHAR(50) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_competitor_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_competitor_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competition_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `competition_result` ;

CREATE TABLE IF NOT EXISTS `competition_result` (
  `code` INT NOT NULL,
  `user_id` INT NOT NULL,
  `vote` VARCHAR(45) NULL,
  PRIMARY KEY (`code`, `user_id`),
  INDEX `fk_competition_has_competitor_competitor1_idx` (`user_id` ASC),
  INDEX `fk_competition_has_competitor_competition1_idx` (`code` ASC),
  CONSTRAINT `fk_competition_has_competitor_competition1`
    FOREIGN KEY (`code`)
    REFERENCES `competition` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competition_has_competitor_competitor1`
    FOREIGN KEY (`user_id`)
    REFERENCES `competitor` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `competitor_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `competitor_test` ;

CREATE TABLE IF NOT EXISTS `competitor_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `img_src` VARCHAR(45) NOT NULL,
  `vote` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `camping_spot`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (1, 'LVA', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (2, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (3, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (4, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (5, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (6, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (7, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (8, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (9, 'LVA', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (10, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (11, 'LVA', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (12, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (13, 'LVA', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (14, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (15, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (16, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (17, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (18, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (19, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (20, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (21, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (22, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (23, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (24, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (25, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (26, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (27, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (28, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (29, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (30, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (31, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (32, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (33, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (34, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (35, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (36, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (37, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (38, 'LVB', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (39, 'LVB', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (40, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (41, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (42, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (43, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (44, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (45, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (46, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (47, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (48, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (49, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (50, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (51, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (52, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (53, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (54, 'LVC', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (55, 'LVC', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (56, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (57, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (58, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (59, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (60, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (61, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (62, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (63, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (64, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (65, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (66, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (67, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (68, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (69, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (70, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (71, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (72, 'LVD', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (73, 'LVD', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (74, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (75, 'LVE', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (76, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (77, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (78, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (79, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (80, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (81, 'LVE', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (82, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (83, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (84, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (85, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (86, 'LVE', 1);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (87, 'LVE', 0);
INSERT INTO `camping_spot` (`spot_id`, `location`, `status`) VALUES (88, 'LVE', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `competitor_test`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (0, 'Mike', 'chef_01_mike.png', 19);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (1, 'Maria', 'chef_02_maria.png', 14);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (2, 'Alan', 'chef_03_alan.png', 23);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (3, 'Michael', 'chef_04_michael.png', 31);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (4, 'Chong', 'chef_05_chong.png', 25);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (5, 'Tina', 'chef_06_tina.png', 25);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (6, 'Ling', 'chef_07_ling.png', 33);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (7, 'Yun', 'chef_08_yun.png', 11);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (8, 'Han', 'chef_09_han.png', 24);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (9, 'Anna', 'chef_10_anna.png', 19);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (10, 'Betty', 'chef_11_betty.png', 15);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (11, 'Gabi', 'chef_12_gabi.png', 20);
INSERT INTO `competitor_test` (`id`, `name`, `img_src`, `vote`) VALUES (12, 'Ishikawa', 'chef_13_ishikawa.png', 13);

COMMIT;

